spring:
  config:
    import: classpath:token.properties

  application:
    name: english

  datasource:
    url: jdbc:postgresql://localhost:5432/english
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create

  web:
    resources:
      add-mappings: false

token:
  signing:
    key: ${token.key}

server:
  port: 8080
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
